### ISSUE TITLE
Line 68

### ISSUE THREAD

**Issue by pjhampton** [PythonProgramming/NLTK-3----Natural-Language-Processing-with-Python-series#1]
Hey Harrison, 

Was just reading though this code base for some ideas.
**Line 68** ~ Should the 2nd parameter not be `save_documents`?

Let me know and I will submit a patch. 

pete

**Comment by Sentdex** [comment]
Which file is this in reference to?

**Comment by pjhampton** [comment]
Damn, sorry. It's **nltkvid19.1.py**

**Comment by Sentdex** [comment]
Yeah, good catch! You're right. Submit away.
